# Generated by Django 5.2.1 on 2025-05-29 03:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='try',
            name='response',
            field=models.CharField(default='o', validators=[django.core.validators.MaxValueValidator(1)], verbose_name='Response'),
        ),
    ]
